### ISSUE TITLE
[synaptic]: authentication popup rejects pwd

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#10]
first popup is probably wrong:
![screenshot_20160724_122528](https://cloud.githubusercontent.com/assets/840070/17084267/e41f5630-51b9-11e6-9f68-192b401882dc.png)

when clicking "Ignore" a second popup comes up where pwd actually works:
![screenshot_20160724_122552](https://cloud.githubusercontent.com/assets/840070/17084270/eb956cb0-51b9-11e6-9520-7c96dd541877.png)

**Comment by davidedmundson** [comment]
We have two things trying to make synaptic run as root.

KDE has a solution (since KDE3.x) where if the .desktop file has the entry
X-KDE-SubstituteUID=true we use kdesu to run the app as root 

------------

Synaptic upstream (presumably recently) added a wrapper binary
synaptic-pkexec

which consists of running the line
"pkexec synaptic"

pkexec under KDE will run the KDE polkit dialog to launch synaptic as root.

Now for some reason we have 3 synaptic .desktop files:
------------
/usr/share/applications/synaptic-kde
has 
X-KDE-SubstituteUID=yes
Exec=synaptic

-----

/usr/share/applications/synaptic

has
Exec=synaptic-pkexec

-----
/usr/share/default-settings/plasma5-profile/applications/synaptics-kde.desktop
has
X-KDE-SubstituteUID=yes
Exec=synaptic-exec

Which is a combo of bad. (and therefore wrong).

I would suggest to remove the X-KDE-SubstituteUID line.

This file is from default-settings-applications which is in ds9-common.

**Comment by llelectronics** [comment]
Removed the 
X-KDE-SubstituteUID=yes

from default-settings-applications. 
Let's hope that fixes the issue

**Comment by star-buck** [comment]
seems to work on netrunner and maui
